before_install:
- echo -e "machine git.smarpsocial.com\n  login truongsinh\n  password $CI_USER_PASSWORD" >> ~/.netrc
- git clone https://git.smarpsocial.com/smarp/MovingHelper.git a/
- mv a/* .

language: objective-c  #1
osx_image: xcode6.4 #2
xcode_project: MovingHelper.xcodeproj #3
xcode_scheme: MovingHelper #4
xcode_sdk: iphonesimulator8.4 #5
